JLink: Add serial number argument to specify flashing target
tock/tockloader pull request #118
Opened 2024-11-07 17:10 UTC by tyler-potyondy

## Overview

Treadmill / CI tests that evaluate networking attach multiple boards to one machine. This PR adds a Tockloader flag (`jlink-serial-no`) to specify the JLink serial number of the device that should be flashed.

This utilizes JLink's command to specify the serial number of the target.

2024-11-07 18:32 UTC, bradjc requested changes

2024-11-07 18:32 UTC, bradjc commented on tockloader/jlinkexe.py
> +                "" if self.jlink_serial_no is None else self.jlink_serial_no,
Please move this to a normal if statement above.

2024-11-07 18:32 UTC, bradjc commented on tockloader/jlinkexe.py
> +                jlink_command += " -USB {} ".format(self.jlink_serial_no)
Remove trailing space.

2024-11-07 18:32 UTC, bradjc commented on tockloader/jlinkexe.py
> +        jtag_p = subprocess.Popen(
Huh?

2024-11-07 18:32 UTC, bradjc commented on README.md
> +- `--jlink-serial-no`: This selects which attached JLink device Tockloader is to
Please move to section on Jlink.

2024-11-07 18:32 UTC, bradjc commented on tockloader/main.py
> +        "--jlink-serial-no",
Do we need "no"? Either remove it or make it "number"

2024-11-07 18:32 UTC, bradjc commented on tockloader/jlinkexe.py
> +        # Obtain serial number if --jlink_serial_no argument provided
Correct the flag name.

2024-11-07 18:51 UTC, tyler-potyondy commented on tockloader/jlinkexe.py
> +        jtag_p = subprocess.Popen(
I don't entirely remember why this is here... I made these changes ~6 months ago but forgot to create the PR. I think this may have been an artifact of testing / debugging and shouldn't be here.

2024-11-07 20:15 UTC, tyler-potyondy commented on tockloader/jlinkexe.py
> +        # Obtain serial number if --jlink_serial_no argument provided
Fixed.

2024-11-07 20:15 UTC, tyler-potyondy commented on tockloader/main.py
> +        "--jlink-serial-no",
Fixed.

2024-11-07 20:26 UTC, tyler-potyondy commented
Alright, should be good to go. @bradjc  I think I fixed all the todos.

2024-11-07 20:28 UTC, bradjc commented on README.md
> +
Why is this a separate paragraph?

2024-11-07 22:29 UTC, tyler-potyondy commented on README.md
> +
I was following the formatting above for this as a code block. Should I alter this?

2024-11-08 17:09 UTC, ppannuto commented on README.md
> +
No, it's right / necessary for the markdown to render correctly.

Without space before 203:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/51e4acde-ca9b-458f-a5ac-03ff61cd1cf2">

Without space before 207:
<img width="878" alt="image" src="https://github.com/user-attachments/assets/e09f1082-3ff3-41d1-a38e-ddda89ce3225">

As-is:
<img width="857" alt="image" src="https://github.com/user-attachments/assets/7c2ee4be-1afa-405b-beb9-954d9f863de9">

2024-11-08 17:12 UTC, ppannuto reviewed
Two small typo-level things; otherwise lgtm √

2024-11-08 17:19 UTC, tyler-potyondy commented on tockloader/main.py
> +        help="Specify a specific JLink via serial number. Useful when multiple JLinks connected to same machine.",
Fixed.

2024-11-08 17:19 UTC, tyler-potyondy commented on tockloader/jlinkexe.py
> +        # Include serial number specifier if `--jlin-serial-number` flag provided.
Fixed.

2024-11-08 17:49 UTC, ppannuto approved these changes

2024-11-09 15:22 UTC, lschuermann approved these changes

2024-11-09 15:22 UTC, lschuermann commented on tockloader/jlinkexe.py
> +                jlink_command += " -USB {}".format(self.jlink_serial_number)
Eh, I guess this could lead to weird errors if you happen to supply a "serial number" with spaces or other weird characters in there. On the other hand, I don't think we should sanitize these inputs, so this seems good to me.

2024-11-11 22:38 UTC, bradjc commented on README.md
> +
No sorry I meant this is a jlink option (and only jlink) and should go with the --jlink example above.

2024-12-11 02:22 UTC, bradjc approved these changes

2024-12-11 02:23 UTC, merged